id: IF73052F3
legacy_id: P006824
ocr_import_info:
  bdrc_scan_id: W1CZ2485
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T12:05:38'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T19:19:47.655586+00:00'
last_modified: 2022-08-31 03:20:32.862079
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ2485
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ2485
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཕྱག་ཆེན་ལྷན་ཅིག་སྐྱེས་སྦྱོར་ཟབ་དོན་ལམ་གྱི་སྙིང་པོ་གྲུབ་ཐོབ་བརྒྱུད་པའི་ཞལ་ལུང་།
  author: ཟུར་མང་དྲུང་པ ༠༤་ཀུན་དགའ་རྣམ་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.5954964235388613
  ocr_word_median_confidence_index: 0.6200000047683716
quality: null
bases:
  I1CZ2495:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ2495
      total_pages: 534
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ2495.txt
    statistics:
      ocr_word_median_confidence_index: 0.6200000047683716
      ocr_word_mean_confidence_index: 0.5954964235388613
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
